"""Assessment Year 2025-26 (Financial Year 2024-25) – Finance Act 2024 & Finance (No. 2) Act 2024.

Key features of this year:
* Section 115BAC (new regime) slabs revised; standard deduction ₹75,000 under the new regime.
* Capital-gains regime changed for transfers on/after 23 July 2024 (111A 20%, 112A 12.5%, 112 12.5%).
* LTCG 112A exemption raised to ₹1,25,000 for the whole year.
* Return due date for non-audit individuals extended from 31 Jul 2025 to 15/16 Sep 2025 (CBDT).
"""
from __future__ import annotations

from datetime import date

from app.models.common import AgeCategory

from .base import (
    CII,
    NEW_ALLOWED_VIA,
    NEW_SURCHARGE,
    OLD_ALLOWED_VIA,
    OLD_REGIME_SLABS,
    OLD_SURCHARGE,
    AdvanceTaxInstalment,
    AYRules,
    CapitalGainRate,
    D,
    HoldingPeriodRule,
    RebateRule,
    RegimeRules,
    Slab,
    TdsThreshold,
    instalments_for_fy,
    standard_deduction_limits,
)

NEW_SLABS_AY2526 = [
    Slab(lower=D(0), upper=D(300000), rate=D("0")),
    Slab(lower=D(300000), upper=D(700000), rate=D("0.05")),
    Slab(lower=D(700000), upper=D(1000000), rate=D("0.10")),
    Slab(lower=D(1000000), upper=D(1200000), rate=D("0.15")),
    Slab(lower=D(1200000), upper=D(1500000), rate=D("0.20")),
    Slab(lower=D(1500000), upper=None, rate=D("0.30")),
]

CG_CHANGE = date(2024, 7, 23)

RULES = AYRules(
    assessment_year="2025-26",
    financial_year="2024-25",
    fy_start=date(2024, 4, 1),
    fy_end=date(2025, 3, 31),
    version="AY2025-26/v1.0",
    status="FINAL",
    sources=[
        "Income-tax Act, 1961 as amended by the Finance Act, 2024 and Finance (No. 2) Act, 2024",
        "Section 115BAC(1A) – rates for AY 2025-26",
        "CBDT Circular 06/2025 – extension of due date to 15 September 2025 (further extended to 16 September 2025)",
        "Cost Inflation Index notification for FY 2024-25 (363)",
    ],
    due_date_individual=date(2025, 9, 16),
    due_date_note="Statutory date 31 July 2025; extended by CBDT to 15 Sep 2025 and then 16 Sep 2025.",
    cess_rate=D("0.04"),
    old=RegimeRules(
        code="OLD",
        label="Old regime (normal provisions)",
        section="Normal provisions of the Act",
        slabs=OLD_REGIME_SLABS,
        standard_deduction_salary=D(50000),
        rebate=RebateRule(income_threshold=D(500000), max_rebate=D(12500), marginal_relief=False),
        surcharge_bands=OLD_SURCHARGE,
        surcharge_cap_on_special_income=D("0.15"),
        professional_tax_deductible=True,
        hra_lta_exemption_allowed=True,
        self_occupied_interest_limit=D(200000),
        hp_loss_setoff_limit=D(200000),
        family_pension_deduction_cap=D(15000),
        chapter_via_allowed_sections=OLD_ALLOWED_VIA,
        employer_nps_rate=D("0.10"),
        notes=["Age-based basic exemption applies to resident senior / super-senior citizens."],
    ),
    new=RegimeRules(
        code="NEW",
        label="New regime (section 115BAC)",
        section="115BAC(1A)",
        slabs={AgeCategory.GENERAL: NEW_SLABS_AY2526, AgeCategory.SENIOR: NEW_SLABS_AY2526,
               AgeCategory.SUPER_SENIOR: NEW_SLABS_AY2526},
        standard_deduction_salary=D(75000),
        rebate=RebateRule(income_threshold=D(700000), max_rebate=D(25000), marginal_relief=True),
        surcharge_bands=NEW_SURCHARGE,
        surcharge_cap_on_special_income=D("0.15"),
        professional_tax_deductible=False,
        hra_lta_exemption_allowed=False,
        self_occupied_interest_limit=D(0),
        hp_loss_setoff_limit=D(0),
        family_pension_deduction_cap=D(25000),
        chapter_via_allowed_sections=NEW_ALLOWED_VIA,
        employer_nps_rate=D("0.14"),
        notes=["Default regime from AY 2024-25. Most exemptions and Chapter VI-A deductions are not available.",
               "Surcharge capped at 25%."],
    ),
    default_regime="NEW",
    senior_age=60,
    super_senior_age=80,
    ltcg_112a_exemption=D(125000),
    capital_gain_rates=[
        CapitalGainRate(bucket="STCG_111A", effective_from=date(2024, 4, 1), rate=D("0.15"),
                        label="STCG on STT-paid equity – 15% (transfer before 23 Jul 2024)"),
        CapitalGainRate(bucket="STCG_111A", effective_from=CG_CHANGE, rate=D("0.20"),
                        label="STCG on STT-paid equity – 20% (transfer on/after 23 Jul 2024)"),
        CapitalGainRate(bucket="STCG_OTHER", effective_from=date(2024, 4, 1), rate=None,
                        label="Other short-term gains – slab rates"),
        CapitalGainRate(bucket="LTCG_112A", effective_from=date(2024, 4, 1), rate=D("0.10"),
                        label="LTCG on STT-paid equity – 10% above exemption (before 23 Jul 2024)"),
        CapitalGainRate(bucket="LTCG_112A", effective_from=CG_CHANGE, rate=D("0.125"),
                        label="LTCG on STT-paid equity – 12.5% above exemption (on/after 23 Jul 2024)"),
        CapitalGainRate(bucket="LTCG_112", effective_from=date(2024, 4, 1), rate=D("0.20"), indexation=True,
                        label="LTCG on other assets – 20% with indexation (before 23 Jul 2024)"),
        CapitalGainRate(bucket="LTCG_112", effective_from=CG_CHANGE, rate=D("0.125"),
                        label="LTCG on other assets – 12.5% without indexation (on/after 23 Jul 2024)"),
        CapitalGainRate(bucket="LTCG_112_INDEXED", effective_from=date(2024, 4, 1), rate=D("0.20"), indexation=True,
                        label="Option for land/building acquired before 23 Jul 2024 – 20% with indexation"),
    ],
    holding_periods=[
        HoldingPeriodRule(asset_classes=["LISTED_EQUITY", "EQUITY_MF", "LISTED_BOND"], months=12,
                          effective_from=date(2024, 4, 1)),
        HoldingPeriodRule(asset_classes=["UNLISTED_SHARES", "IMMOVABLE_PROPERTY"], months=24,
                          effective_from=date(2024, 4, 1)),
        HoldingPeriodRule(asset_classes=["DEBT_MF", "GOLD", "OTHER"], months=36, effective_from=date(2024, 4, 1)),
        HoldingPeriodRule(asset_classes=["DEBT_MF", "GOLD", "OTHER"], months=24, effective_from=CG_CHANGE),
    ],
    specified_mf_cutoff=date(2023, 4, 1),
    cii=CII,
    deduction_limits=standard_deduction_limits(),
    presumptive_44ada_rate=D("0.50"),
    presumptive_44ada_limit=D(5000000),
    presumptive_44ada_limit_digital=D(7500000),
    presumptive_44ad_rate_cash=D("0.08"),
    presumptive_44ad_rate_digital=D("0.06"),
    presumptive_44ad_limit=D(20000000),
    presumptive_44ad_limit_digital=D(30000000),
    interest_rate_234a=D("0.01"),
    interest_rate_234b=D("0.01"),
    interest_rate_234c=D("0.01"),
    advance_tax_threshold=D(10000),
    advance_tax_instalments=instalments_for_fy(2024),
    presumptive_instalment=AdvanceTaxInstalment(due_on=date(2025, 3, 15), cumulative_pct=D("1.00"),
                                                 interest_months=1),
    tds_thresholds={
        "194A_BANK": TdsThreshold(section="194A", label="Interest from banks / post office / co-op",
                                  threshold=D(40000), senior_threshold=D(50000), rate=D("0.10")),
        "194A_OTHER": TdsThreshold(section="194A", label="Other interest", threshold=D(5000), rate=D("0.10")),
        "194": TdsThreshold(section="194", label="Dividend", threshold=D(5000), rate=D("0.10")),
        "194H": TdsThreshold(section="194H", label="Commission / brokerage", threshold=D(15000), rate=D("0.02")),
        "194J": TdsThreshold(section="194J", label="Professional fees", threshold=D(30000), rate=D("0.10")),
        "194I": TdsThreshold(section="194-I", label="Rent (business payer)", threshold=D(240000), rate=D("0.10")),
        "194IB": TdsThreshold(section="194-IB", label="Rent by individuals (per month)", threshold=D(50000),
                              rate=D("0.05")),
    },
    itr1_income_limit=D(5000000),
    itr1_ltcg_112a_limit=D(125000),
)
